### ISSUE TITLE
Error "enterprise_catalog_product_rewrite" table not found

### ISSUE THREAD

**Issue by erfanimani** [EcomDev/sync-magento-2-migration#5]
There's a hard reference to Magento Enterprise tables here, causing issues with product export:

https://github.com/EcomDev/sync-magento-2-migration/blob/main/src/ProductInfo.php#L408

I managed to get around it by excluding product URL rewrites, and generating rewrites using this: https://github.com/elgentos/regenerate-catalog-urls

Should there be a check to see if that table exists and/or the current version is Enterprise?

**Comment by IvanChepurnyi** [comment]
true, this one is based on m1 with EE database structure. It is however possible to use core_url_rewrite table for export, but don't have yet time to make it happen.

**Comment by erfanimani** [comment]
The implementation solution is to check for table existence, if the enterprise table doesn't exist, switch to using core_url_rewrite
